// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-IOoI3YDdfmb0Z-ItR4ZU9LM2ZgElazI',
    appId: '1:23240856888:web:ea9cc5ae61f59d9174ddcd',
    messagingSenderId: '23240856888',
    projectId: 'spottyclone',
    authDomain: 'spottyclone-d63e4.firebaseapp.com',
    storageBucket: 'spottyclone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcagCW4-jIUX52AOlcYpcx9tBpFdC9Yw',
    appId: '1:23240856888:ios:c397b74f44fdc0c774ddcd',
    messagingSenderId: '23240856888',
    projectId: 'spottyclone',
    storageBucket: 'spottyclone.firebasestorage.app',
    iosBundleId: 'com.spotifyclone.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkcagCW4-jIUX52AOlcYpcx9tBpFdC9Yw',
    appId: '1:23240856888:ios:c397b74f44fdc0c774ddcd',
    messagingSenderId: '23240856888',
    projectId: 'spottyclone',
    storageBucket: 'spottyclone.firebasestorage.app',
    iosBundleId: 'com.spotifyclone.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-IOoI3YDdfmb0Z-ItR4ZU9LM2ZgElazI',
    appId: '1:23240856888:web:3a036e30d90d31fa74ddcd',
    messagingSenderId: '23240856888',
    projectId: 'spottyclone',
    authDomain: 'spottyclone-d63e4.firebaseapp.com',
    storageBucket: 'spottyclone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKGh8gFxJgfZqe4nyAw3-hd6ZCDZD80I',
    appId: '1:23240856888:android:4fe1ee8bbb2d7cf274ddcd',
    messagingSenderId: '23240856888',
    projectId: 'spottyclone',
    storageBucket: 'spottyclone.firebasestorage.app',
  );

}